Reformatted with current IntelliJ code style (#993)

diff --git a/.github/workflows/build-check-publish.yml b/.github/workflows/build-check-publish.yml
--- a/.github/workflows/build-check-publish.yml
+++ b/.github/workflows/build-check-publish.yml
@@ -58,16 +58,16 @@ jobs:
         with:
           build-root-directory: yona-server
           arguments: |
-              check
-              sonarqube
-              --info
+            check
+            sonarqube
+            --info
       - name: Build Docker images
         uses: gradle/gradle-build-action@v2.3.3
         with:
           build-root-directory: yona-server
           arguments: |
-              -PdockerUrl=unix:///var/run/docker.sock
-              buildDockerImage
+            -PdockerUrl=unix:///var/run/docker.sock
+            buildDockerImage
       - name: Checkout Helm chart repo for PR
         if: ${{ inputs.is-pr-build }}
         uses: actions/checkout@v3
@@ -159,12 +159,12 @@ jobs:
         with:
           build-root-directory: yona-server
           arguments: |
-              --no-daemon
-              -Pyona_adminservice_url=http://localhost:31000
-              -Pyona_analysisservice_url=http://localhost:31001
-              -Pyona_appservice_url=http://localhost:31002
-              -Pyona_batchservice_url=http://localhost:31003
-              intTest
+            --no-daemon
+            -Pyona_adminservice_url=http://localhost:31000
+            -Pyona_analysisservice_url=http://localhost:31001
+            -Pyona_appservice_url=http://localhost:31002
+            -Pyona_batchservice_url=http://localhost:31003
+            intTest
       - name: Gather logs
         if: always()
         run: |
@@ -189,18 +189,18 @@ jobs:
         uses: EnricoMi/publish-unit-test-result-action@v1.40
         with:
           files: |
-           **/build/test-results/test/*.xml
-           **/build/test-results/intTest/*.xml
+            **/build/test-results/test/*.xml
+            **/build/test-results/intTest/*.xml
       - name: Publish Docker images
         if: ${{ !inputs.is-pr-build }}
         uses: gradle/gradle-build-action@v2.3.3
         with:
           build-root-directory: yona-server
           arguments: |
-              -PdockerHubUserName=${{ secrets.DOCKER_HUB_USER_NAME }}
-              -PdockerHubPassword=${{ secrets.DOCKER_HUB_PASSWORD }}
-              -PdockerUrl=unix:///var/run/docker.sock
-              pushDockerImage
+            -PdockerHubUserName=${{ secrets.DOCKER_HUB_USER_NAME }}
+            -PdockerHubPassword=${{ secrets.DOCKER_HUB_PASSWORD }}
+            -PdockerUrl=unix:///var/run/docker.sock
+            pushDockerImage
       - name: Publish Helm package
         if: ${{ !inputs.is-pr-build }}
         working-directory: yona-server/k8s/helm
@@ -226,23 +226,23 @@ jobs:
           git config --global user.name "${GIT_AUTHOR_NAME}"
           git tag --force --annotate build-${{ inputs.build-id }} -m "GitHub build"
           git push -f https://github.com/yonadev/yona-server.git refs/tags/build-${{ inputs.build-id }}
-      - name : Wait for Helm package to become available on GitHub pages
+      - name: Wait for Helm package to become available on GitHub pages
         if: ${{ !inputs.is-pr-build }}
         run: |
-            maxWaitTime=600 # GitHub: Note: It can take up to 10 minutes for changes to your site to publish
-            sleepDuration=5
-            totalSleepDuration=0
-            while (( totalSleepDuration < maxWaitTime )); do
-              if curl --output /dev/null --silent --head --fail https://yonadev.github.io/helm-charts/yona-1.2.${{ inputs.build-id }}.tgz; then
-                      echo Helm chart is available after ${totalSleepDuration} seconds
-                exit 0
-              else
-                sleep ${sleepDuration}
-                ((totalSleepDuration+=sleepDuration))
-              fi
-            done
-            echo "ERROR: Helm chart is NOT available after ${totalSleepDuration} seconds"
-            exit 1
+          maxWaitTime=600 # GitHub: Note: It can take up to 10 minutes for changes to your site to publish
+          sleepDuration=5
+          totalSleepDuration=0
+          while (( totalSleepDuration < maxWaitTime )); do
+            if curl --output /dev/null --silent --head --fail https://yonadev.github.io/helm-charts/yona-1.2.${{ inputs.build-id }}.tgz; then
+                    echo Helm chart is available after ${totalSleepDuration} seconds
+              exit 0
+            else
+              sleep ${sleepDuration}
+              ((totalSleepDuration+=sleepDuration))
+            fi
+          done
+          echo "ERROR: Helm chart is NOT available after ${totalSleepDuration} seconds"
+          exit 1
       - name: Publish Gradle dependencies
         if: ${{ !inputs.is-pr-build }}
         uses: mikepenz/gradle-dependency-submission@v0.8.3
