Add action to wait for Helm chart to become available

diff --git a/.github/workflows/build-check-publish.yml b/.github/workflows/build-check-publish.yml
--- a/.github/workflows/build-check-publish.yml
+++ b/.github/workflows/build-check-publish.yml
@@ -186,6 +186,23 @@ jobs:
           git config --global user.name "${GIT_AUTHOR_NAME}"
           git tag --force --annotate build-${{ inputs.build-id }} -m "GitHub build"
           git push https://github.com/yonadev/yona-server.git --tags
+      - name : Wait for Helm package to become available on GitHub pages
+        run: |
+            maxWaitTime=10 # GitHub: Note: It can take up to 10 minutes for changes to your site to publish
+            sleepDuration=5
+            totalSleepDuration=0
+            while (( totalSleepDuration < maxWaitTime )); do
+              # if curl --output /dev/null --silent --head --fail https://yonadev.github.io/helm-charts/yona-1.2.${{ inputs.build-id }}.tgz; then
+              if curl --output /dev/null --silent --head --fail https://yonadev.github.io/helm-charts/yona-1.2.TODO.tgz; then
+                      echo Helm chart is available after ${totalSleepDuration} seconds
+                exit 0
+              else
+               sleep ${sleepDuration}
+               ((totalSleepDuration+=sleepDuration))
+              fi
+            done
+            echo "ERROR: Helm chart is NOT available after ${totalSleepDuration} seconds"
+            exit 1
       - name: Notify PR build success through Slack
         if: ${{ success() && inputs.is-pr-build }}
         uses: slackapi/slack-github-action@v1.19.0
